config:
  send_anonymous_usage_stats: false

warehouse:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('DBT_ENV_SECRET_SNOWFLAKE_ACCOUNT') }}"

      user: "{{ env_var('DBT_ENV_SECRET_USER') }}"
      password: "{{ env_var('DBT_ENV_SECRET_PASSWORD') }}"
      # authenticator: username_password_mfa # Enable if using DUO MFA authentication

      role: "{{ env_var('DBT_ENV_SECRET_ROLE') }}"
      database: "{{ env_var('DBT_ENV_SECRET_DATABASE') }}"
      warehouse: "{{ env_var('DBT_ENV_SECRET_WAREHOUSE') }}"
      schema: "{{ env_var('DBT_ENV_SECRET_SCHEMA') }}"

      threads: 8
      query_tag: dbt_dev
